language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "pypy3.5"

# command to install dependencies
install:
  - pip install -r requirements-dev.txt

# command to run tests
script:
  - true
#  - pytest