language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "pypy3.5"

# command to install dependencies
install:
  - pip install -r requirements-test.txt

# command to run tests
script:
  - true
#  - pytest

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
    - http://dependencies-ai-coe.apps.ci.centos.org/webhooks/travis-ci
    on_success: always 
    on_failure: always
    on_start: always 