apiVersion: v1
kind: Template
metadata:
  name: api-service
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: dependency-monkey
    name: api-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: api-service
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: dependency-monkey
    name: api-service
  spec:
    replicas: 1
    selector:
      deploymentconfig: api-service
    template:
      metadata:
        labels:
          app: dependency-monkey
          deploymentconfig: api-service
      spec:
        containers:
          image: " "
          imagePullPolicy: Always
          name: api-service
          ports:
          - containerPort: 8080
            protocol: TCP
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - api-service
        from:
          kind: ImageStreamTag
          name: api-service:latest
          namespace: thoth-dev
      type: ImageChange
    - type: ConfigChange