apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: dependency-monkey
  name: api-service
spec:
  output:
    to:
      kind: ImageStreamTag
      name: api-service:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: feature/pymongo
      uri: https://github.com/goern/thoth-dependency-monkey
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.5
        namespace: openshift
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange