apiVersion: v1
kind: Template
metadata:
  name: api-service
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: dependency-monkey
    name: api-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: api-service
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: dependency-monkey
    name: api-service
  spec:
    replicas: 1
    selector:
      app: dependency-monkey
      deploymentconfig: api-service
    template:
      metadata:
        labels:
          app: dependency-monkey
          deploymentconfig: api-service
      spec:
        containers:
        - name: api-service
          image: " "
          imagePullPolicy: Always
          serviceAccountName: validation-job-runner
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: THOTH_DEPENDENCY_MONKEY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - api-service
        from:
          kind: ImageStreamTag
          name: api-service:latest
          namespace: ai-coe
      type: ImageChange
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: api-service
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
