apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: dependency-monkey
  name: dependency-monkey-api
spec:
  output:
    to:
      kind: ImageStreamTag
      name: dependency-monkey-api:test
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/AICoE/thoth-dependency-monkey
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.5
        namespace: openshift
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange