apiVersion: v1
kind: Template
metadata:
  name: pypi-validator
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: pypi-validator
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: dependency-monkey
    name: pypi-validator
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: pypi-validator:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: feature/pypi-validator-image
        uri: https://github.com/goern/thoth-dependency-monkey
      type: Git
      contextDir: images/pypi-validator
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange