apiVersion: v1
kind: Template
labels:
  template: thoth-dependency-monkey-api-buildconfig
  thoth: 0.1.0
metadata:
  name: thoth-dependency-monkey-api-buildconfig
  annotations:
    description: This is Thoth Dependency Monkey API BuildConfig, this template is meant to be used by Jenkins, but could also be used by humans...
    openshift.io/display-name: Thoth Dependency Monkey API BuildConfig
    version: 0.1.0
    tags: poc,thoth,thoth-dependency-monkey-api,ai-stacks
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: This is Thoth Dependency Monkey API BuildConfig, this template is meant to be used by Jenkins, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
#
# Image streams
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: dependency-monkey
    name: dependency-monkey-api
  spec:
    lookupPolicy:
      local: true
    name: stable

- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: dependency-monkey
    name: pypi-validator
  spec:
    lookupPolicy:
      local: true
    name: stable

#
# Build configs
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: dependency-monkey-api
    labels:
      app: dependency-monkey
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "dependency-monkey-api:${IMAGE_STREAM_TAG}"
    source:
      type: Git
      git:
        uri: ${THOTH_DEPENDENCY_MONKEY_API_GIT_URL}
        ref: ${THOTH_DEPENDENCY_MONKEY_API_GIT_REF}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:latest
    triggers:
    - type: ImageChange
      imageChange: {}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: dependency-monkey
    name: pypi-validator
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "pypi-validator:${IMAGE_STREAM_TAG}"
    source:
      type: Git
      git:
        uri: ${THOTH_DEPENDENCY_MONKEY_API_GIT_URL}
        ref: ${THOTH_DEPENDENCY_MONKEY_API_GIT_REF}
      contextDir: images/pypi-validator
    strategy:
      type: Docker

parameters:
- description: Git repository for Thoth's Dependency Monkey API
  displayName: Thoth Dependency Monkey git repository
  required: true
  name: THOTH_DEPENDENCY_MONKEY_API_GIT_URL
  value: 'https://github.com/AICoE/thoth-dependency-monkey'

- description: Git repository for Thoth's Dependency Monkey API
  displayName: Thoth Dependency Monkey git reference
  required: true
  name: THOTH_DEPENDENCY_MONKEY_API_GIT_REF
  value: 'master'

- description: Tag of the output ImageStream the resulting container image should go to
  displayName: ImageStream Tag
  required: true
  name: IMAGE_STREAM_TAG
  value: 'latest'